apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  replicas: 1
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:1.0.1
          ports:
            # exposing dynamodb
            - containerPort: 31001
            # exposing sqs
            - containerPort: 31000
            # expsosing the localstack ui
            - containerPort: 32000
          env:
            # with the SERVICES environment variable, you can tell LocalStack
            # what services to expose on what port
            - name: SERVICES
              value: "sqs,sns:31000,dynamodb:31001"
            - name: PORT_WEB_UI
              value: "32000"

---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  # selector tells Kubernetes what Deployment this Service
  # belongs to
  type: NodePort
  selector:
    app: localstack
  ports:
    - port: 32000
      protocol: TCP
      name: ui
      nodePort: 32000
    - port: 31001
      protocol: TCP
      name: dynamodb
      nodePort: 31001
    - port: 31000
      protocol: TCP
      name: sqs
      nodePort: 31000
    - port: 4566
      protocol: TCP
      name: all
