---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
 name: teams-api
spec:
  selector:
    matchLabels:
      {{- include "lab-api-teams.selectorLabels" . | nindent 6 }}
  jwtRules:
  - issuer: {{ .Values.jwt_issuer| quote }}
    jwksUri: "{{- .Values.jwt_issuer }}.well-known/jwks.json"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
spec:
  selector:
    matchLabels:
      {{- include "lab-api-teams.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
       requestPrincipals: ["{{- .Values.jwt_issuer }}*"]
